accountapp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from accountapp.views import hello_world, AccountCreateView, AccountDetailView, AccountUpdateView, AccountDeleteView, \
    test

app_name = "accountapp"

urlpatterns = [
    path('hello_world/', hello_world, name='hello_world'),
    path('test/', test, name='test'),

    path('create/', AccountCreateView.as_view(), name='create'),

    path('login/', LoginView.as_view(template_name='accountapp/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),

    path('detail/<int:pk>', AccountDetailView.as_view(), name='detail'),
    path('update/<int:pk>', AccountUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', AccountDeleteView.as_view(), name='delete'),
]

pragmatic/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accountapp.urls')),
    path('profiles/', include('profileapp.urls')),
]

profileapp/urls.py
from django.urls import path

app_name = "profileapp"

urlpatterns = [
]

accountapp/models.py
from django.db import models


class HelloWorld(models.Model):
    text = models.CharField(max_length=255, null=False)

profileapp/models.py
from django.contrib.auth.models import User
from django.db import models


class Profile(models.Model):
    # OneToOneField: User와 Profile을 일대일 매칭한다.
    # CASCADE: User가 삭제되면 Profile도 삭제된다.
    # related_name: API 요청시 request.user.profile 으로 단번에 프로필 정보를 얻을 수 있다.
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')

    # upload_to: 파일이 저장되는 중간 경로 설정. image는 media/profile/ 디렉토리 하위에 저장된다.
    image = models.ImageField(upload_to='profile/', null=True)

    # 유저는 닉네임 정보는 unique하다. (중복 X)
    nickname = models.CharField(max_length=20, unique=True, null=True)
    message = models.CharField(max_length=100, null=True)

accountapp/forms.py
from django.contrib.auth.forms import UserCreationForm


class AccountUpdateForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['username'].disabled = True

profileapp/forms.py
from django.forms import ModelForm

from profileapp.models import Profile


# django의 ModelForm을 이용하면 기존의 Model을 Form으로 자동 변환해서 사용할 수 있다.
class ProfileCreationForm(ModelForm):
    class Meta:
        # Profile이라는 모델을 가져와서 Form으로 사용하겠다.
        model = Profile
        # Profile 모델에서 image, nickname, message 컬럼만 가져와서 사용하겠다.
        fields = ['image', 'nickname', 'message']

accountapp/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, DetailView, DeleteView, UpdateView

from accountapp.decorator import account_ownership_required
from accountapp.forms import AccountUpdateForm
from accountapp.models import HelloWorld

# login_required 먼저 순차적으로 실행됨
has_ownership = [login_required, account_ownership_required]


def test(request):
    return render(request, 'accountapp/test.html')


@login_required
def hello_world(request):
    if request.method == "POST":
        text = request.POST.get("hello_world_input")

        # DB 저장
        new_hello_world = HelloWorld()
        new_hello_world.text = text
        new_hello_world.save()

        return HttpResponseRedirect(reverse('accountapp:hello_world'))
    else:
        hello_world_list = HelloWorld.objects.all()
        return render(request, 'accountapp/hello_world.html', context={'hello_world_list': hello_world_list})


class AccountCreateView(CreateView):
    model = User
    form_class = UserCreationForm
    success_url = reverse_lazy('accountapp:login')
    template_name = 'accountapp/create.html'


class AccountDetailView(DetailView):
    model = User
    context_object_name = 'target_user'
    template_name = 'accountapp/detail.html'


@method_decorator(has_ownership, 'get')
@method_decorator(has_ownership, 'post')
class AccountUpdateView(UpdateView):
    model = User
    context_object_name = 'target_user'
    form_class = AccountUpdateForm
    success_url = reverse_lazy('accountapp:hello_world')
    template_name = 'accountapp/update.html'


@method_decorator(has_ownership, 'get')
@method_decorator(has_ownership, 'post')
class AccountDeleteView(DeleteView):
    model = User
    context_object_name = 'target_user'
    success_url = reverse_lazy('accountapp:login')
    template_name = 'accountapp/delete.html'

profileapp/views.py
from django.shortcuts import render

# Create your views here.

accountapp/templates/accountapp/create.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block content %}
<div style="text-align: center; max-width: 500px; margin: 4rem auto;">
    <div class="mb-4">
        <h4>SignUp</h4>
    </div>
    <form action="{% url 'accountapp:create' %}" method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3">
    </form>
</div>
{% endblock %}

accountapp/templates/accountapp/delete.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block content %}
<div style="text-align: center; max-width: 500px; margin: 4rem auto;">
    <div class="mb-4">
        <h4>Quit</h4>
    </div>
    <form action="{% url 'accountapp:delete' pk=target_user.pk %}" method="post">
        {% csrf_token %}
        <input type="submit" class="btn btn-danger rounded-pill col-6 mt-3">
    </form>
</div>
{% endblock %}

accountapp/templates/accountapp/detail.html
{% extends 'base.html' %}

{% block content %}

    <div>
        <div style="text-align: center; max-width: 500px; margin: 4rem auto;">
            <p>
                {{  target_user.date_joined }}
            </p>
            <h2 style="font-family: 'NanumSquareNeo-eHv'">
                {{ target_user.username }}
            </h2>

            {% if target_user == user %}
            <a href="{% url 'accountapp:update' pk=user.pk %}">
                <p>Change Info</p>
            </a>
            <a href="{% url 'accountapp:delete' pk=user.pk %}">
                <p>Delete Account</p>
            </a>
            {% endif %}
        </div>
    </div>

{% endblock %}

accountapp/templates/accountapp/hello_world.html
{% extends "base.html" %}

{% block content %}
    <div style="border-radius: 1rem; margin: 2rem; text-align: center;">
        <h1 class="pragmatic_logo">
            Hello World LIST ~
        </h1>

        <form action="{% url 'accountapp:hello_world' %}" method="post">
            {% csrf_token %}
            <div>
                <input type="text" name="hello_world_input">
            </div>

            <div>
                <input type="submit" class="btn btn-primary" value="POST">
            </div>
        </form>

        {% if hello_world_list %}
            {% for hello_world in hello_world_list%}
            <h4>
                {{ hello_world.text }}
            </h4>
            {% endfor %}
        {% endif %}

    </div>
{% endblock %}

accountapp/templates/accountapp/login.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block content %}
    <div style="text-align: center; max-width: 500px; margin: 4rem auto;">
        <div>
            <h4>Login</h4>
        </div>
        <div>
            <form action="" method="post">
                {% csrf_token %}
<!--                {{ form }}-->
                {% bootstrap_form form %}
                <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3">
            </form>
        </div>
    </div>
{% endblock %}

accountapp/templates/accountapp/test.html
{% extends "base.html" %}

{% block content %}
    <div style="text-align: center;">
        <h1>TEST PAGE</h1>
    </div>
{% endblock %}

accountapp/templates/accountapp/update.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block content %}
<div style="text-align: center; max-width: 500px; margin: 4rem auto;">
    <div class="mb-4">
        <h4>Change Info</h4>
    </div>
    <form action="{% url 'accountapp:update' pk=target_user.pk %}" method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3">
    </form>
</div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="ko">

{% include "head.html" %}

<body style="font-family: 'NanumSquareNeo-aLt';">

    {% include "header.html" %}

    <hr>

    {% block content %}
    {% endblock %}

    <hr>

    {% include "footer.html" %}

</body>
</html>

templates/footer.html
    <div class="pragmatic_footer">

        <div class="pragmatic_footer_button">
            <span>공지사항</span> |
            <span>제휴문의</span> |
            <span>서비스 소개</span>
        </div>

        <div style="margin-top: 1rem;">
            <h6 class="pragmatic_logo">Pragmatic</h6>
        </div>

    </div>

templates/head.html
{% load static %}

<head>
    <meta charset="UTF-8">
    <title>Pragmatic</title>

    <!-- bootstrap link -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

    <!-- google fonts link -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lobster&family=Teko:wght@300..700&display=swap" rel="stylesheet">

    <!-- default css link -->
    <link rel="stylesheet" type="text/css" href="{% static 'base.css' %}">

    <style>
        @font-face {
            font-family: 'NanumSquareNeo-aLt';
            src: local('NanumSquareNeo-aLt'),
            url("{% static 'fonts/NanumSquareNeo-aLt.ttf' %}") format("truetype");
        }
        @font-face {
            font-family: 'NanumSquareNeo-bRg';
            src: local('NanumSquareNeo-bRg'),
            url("{% static 'fonts/NanumSquareNeo-bRg.ttf' %}") format("truetype");
        }
        @font-face {
            font-family: 'NanumSquareNeo-cBd';
            src: local('NanumSquareNeo-cBd'),
            url("{% static 'fonts/NanumSquareNeo-cBd.ttf' %}") format("truetype");
        }
        @font-face {
            font-family: 'NanumSquareNeo-dEb';
            src: local('NanumSquareNeo-dEb'),
            url("{% static 'fonts/NanumSquareNeo-dEb.ttf' %}") format("truetype");
        }
        @font-face {
            font-family: 'NanumSquareNeo-eHv';
            src: local('NanumSquareNeo-eHv'),
            url("{% static 'fonts/NanumSquareNeo-eHv.ttf' %}") format("truetype");
        }
    </style>
</head>

templates/header.html
    <div class="pragmatic_header">

        <div>
            <h1 class="pragmatic_logo">Pragmatic</h1>
        </div>

        <div>
            <span>nav1</span>
            <span>nav2</span>
            <span>nav3</span>
            {% if not user.is_authenticated %}
            <a href="{% url 'accountapp:login' %}?next={{ request.path }}">
                <span>login</span>
            </a>
            <a href="{% url 'accountapp:create' %}">
                <span>sign up</span>
            </a>
            {% else %}
            <a href="{% url 'accountapp:detail' pk=user.pk %}">
                <span>MyPage</span>
            </a>
            <form style="display: inline" action="{% url 'accountapp:logout' %}" method="post">
                {% csrf_token %}
                <input type="submit" class="btn" value="logout">
            </form>
            {% endif %}
        </div>

    </div>